services:
  meu-backend:
    image: rinha:latest
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "250MB"
    networks:
      - backend
      - payment-processor
    ports:
      - "9999:8080"
    environment:
      - ConnectionStrings__default=http://payment-processor-default:8080
      - ConnectionStrings__fallback=http://payment-processor-fallback:8080
      - ConnectionStrings__postgres=Host=rinha-db;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
    depends_on:
      - rinha-db
    # etc...
  rinha-db:
    image: postgres:17-alpine
    networks:
      - payment-processor
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true